version: '3.8'

services:
 
  database:
    image: postgres:14-alpine
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: brinquedos_revisao
    ports:
      - "5432:5432"

  
  app:
    build: .
    container_name: gerenciamento-brinquedos
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/brinquedos_revisao
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=senha_segura
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
