version: '3.9'

services:
  oracle_db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle_db
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: adminpass
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/adminpass@//localhost:1521/XEPDB1 >/dev/null 2>&1"]
      interval: 30s
      timeout: 15s
      retries: 40
      start_period: 180s

  api_spring:
    build: .
    container_name: api_spring
    depends_on:
      oracle_db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle_db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: adminpass
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      retries: 5
      start_period: 20s

volumes:
  oracle_data:

networks:
  backend: