version: '3.9'

services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle_db
    restart: unless-stopped
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: adminpass
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init.sql:/opt/oracle/scripts/startup/init.sql
    networks:
      - brinquedos_net
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/adminpass@//localhost:1521/XEPDB1 >/dev/null 2>&1"]
      interval: 30s
      timeout: 15s
      retries: 40
      start_period: 180s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gerenciamento-de-brinquedos-app
    container_name: api_spring
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - brinquedos_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:

networks:
  brinquedos_net:
    driver: bridge